site_name: Intentional
repo_url: https://github.com/intentional-ai/intentional
site_dir: ../site
docs_dir: "."
theme:
  name: material

nav:
   - 'Home': docs/home.md
   - 'Installation': docs/installation.md
   - 'High-level Concepts': docs/concepts.md
   - 'Configuration File': docs/config-file.md
   - 'Plugins': docs/plugins.md
   - 'API Reference':
      - 'Main Package': docs/reference.md
      - 'Core Package': docs/core-reference.md
      - 'Plugins':
         - 'FastAPI':
            - 'Getting Started': plugins/intentional-fastapi/README.md
            - 'API Reference': plugins/intentional-fastapi/docs/reference.md
         - 'OpenAI':
            - 'Getting Started': plugins/intentional-openai/README.md
            - 'API Reference': plugins/intentional-openai/docs/reference.md
         - 'Pipecat':
            - 'Getting Started': plugins/intentional-pipecat/README.md
            - 'API Reference': plugins/intentional-pipecat/docs/reference.md
         - 'Telegram UI':
            - 'Getting Started': plugins/intentional-telegram/README.md
            - 'API Reference': plugins/intentional-telegram/docs/reference.md
         - 'Terminal':
            - 'Getting Started': plugins/intentional-terminal/README.md
            - 'API Reference': plugins/intentional-terminal/docs/reference.md
         - 'Textual UI':
            - 'Getting Started': plugins/intentional-textual-ui/README.md
            - 'API Reference': plugins/intentional-textual-ui/docs/reference.md
   - 'Contribute': CONTRIBUTING.md
   - 'CLA': docs/cla.md

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
- exclude:
    glob:
      - .venv/*
      - README.md
      - intentional/README.md
      - intentional-core/README.md
      - plugins/README.md
      - header.txt
- redirects:
      redirect_maps:
        'index.md': 'docs/home.md'
- search
- same-dir
- mermaid2:
   version: 10.3.0
- include-markdown
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true

validation:
  omitted_files: warn
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
