site_name: Intentional
repo_url: https://github.com/intentional-ai/intentional
site_dir: ../site
docs_dir: "."
theme:
  name: material

nav:
   - 'Home': docs/home.md
   - 'Contribute': CONTRIBUTING.md
   - 'API Reference - Main Package': docs/reference.md
   - 'API Reference - Core Package': docs/core-reference.md
   - 'Plugins':
     - 'Local Terminal':
        - 'Getting Started': plugins/intentional-terminal/README.md
        - 'API Reference': plugins/intentional-terminal/docs/reference.md
     - 'OpenAI':
        - 'Getting Started': plugins/intentional-openai/README.md
        - 'API Reference': plugins/intentional-openai/docs/reference.md
     - 'Telegram UI':
        - 'Getting Started': plugins/intentional-telegram/README.md
        - 'API Reference': plugins/intentional-telegram/docs/reference.md
     - 'Text Chat':
        - 'Getting Started': plugins/intentional-text-chat/README.md
        - 'API Reference': plugins/intentional-text-chat/docs/reference.md
     - 'Textual UI':
        - 'Getting Started': plugins/intentional-textual-ui/README.md
        - 'API Reference': plugins/intentional-textual-ui/docs/reference.md
     - 'WebSocket':
        - 'Getting Started': plugins/intentional-websocket/README.md
        - 'API Reference': plugins/intentional-websocket/docs/reference.md

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- exclude:
    glob:
      - .venv/*
      - README.md
      - intentional/README.md
      - intentional-core/README.md
      - plugins/README.md
- redirects:
      redirect_maps:
        'index.md': 'docs/home.md'
- search
- same-dir
- include-markdown
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true

validation:
  omitted_files: warn
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
