name: Pre-commit Hooks

on:
  pull_request:
  push:
    branches: [main]

env:
  SKIP: pytest

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install uv
        uv pip install --system intentional-core/ intentional/[dev]
        git fetch origin main

    - name: Run pre-commit hooks
      run: pre-commit run --all -v

  find-plugins:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.folders.outputs.value }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get the affected folders list
        id: folders
        run: |
          git fetch origin main
          echo "value=$(./.github/workflows/scripts/get_affected_folders.sh)" >> $GITHUB_OUTPUT

      - name: "Print affected folders list"
        run: |
          echo "${{ steps.folders.outputs.value }}"

  run-plugins:
    needs:
      - find-plugins
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: ${{fromJSON(needs.find-plugins.outputs.folders)}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install packages
      run: |
        sudo apt-get install portaudio19-dev
        pip install uv
        uv pip install --system intentional-core/ intentional/[test] plugins/${{ matrix.folder }}[lint]

    - name: Run pylint on ${{ matrix.folder }}
      run: pylint -sn -rn --rcfile=plugins/${{ matrix.folder }}/pyproject.toml plugins/${{ matrix.folder }}/src/
