name: Pre-commit Hooks

on:
  pull_request:
  push:
    branches: [main]

env:
  SKIP: pytest

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: pip install intentional-core/[dev]
    - run: pre-commit run --all
