name: Pre-commit Hooks

on:
  pull_request:
  push:
    branches: [main]

env:
  SKIP: pytest

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: pip install intentional-core/[dev]
    - uses: pre-commit/action@v3.0.1
