name: Release

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'The full path to the folder name of the package to release'
        required: true
        default: 'intentional-core/'
  push:
    tags:
    - "v*.*.*"

jobs:

  publish:
    runs-on: ubuntu-latest
    environment: PyPI Publisher
    permissions:
      id-token: write
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install intentional-core/

      - name: Build wheels
        run: python setup.py sdist bdist_wheel

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
