name: Release Core

on:
  workflow_dispatch:
  push:
    tags:
    - "v*.*.*"

jobs:

  publish:
    runs-on: ubuntu-latest
    environment: PyPI Publisher
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install hatch intentional/ intentional-core/

      - name: Build wheels
        run: |
          cd intentional/
          hatch build
          cd ../intentional-core/
          hatch build

      - name: Publish intentional-core to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: intentional-core/dist/

      - name: Publish intentional to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: intentional/dist/
