name: Release All Packages on TestPyPI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  publish-core:
    runs-on: ubuntu-latest
    environment: PyPI Publisher
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system hatch intentional-core/ intentional/

      - name: Build intentional-core wheel
        run: |
          cd intentional-core/
          hatch build
          hatch version $(date +%s)

      - name: Publish intentional-core to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: intentional-core/dist/

      - name: Build intentional wheel
        run: |
          cd intentional/
          hatch build
          hatch version $(date +%s)

      - name: Publish intentional to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: intentional/dist/

      - name: List plugins
        id: list_plugins
        run: |
          git fetch origin main
          echo "value=$(./.github/workflows/scripts/get_affected_folders.sh)" >> $GITHUB_OUTPUT

      - name: "Print plugins list"
        run: |
          echo "${{ steps.list_plugins.outputs.value }}"

  publish-plugins:
    needs: publish-core
    runs-on: ubuntu-latest
    environment: PyPI Publisher
    permissions:
      id-token: write
    strategy:
      matrix:
        plugin: ${{fromJson(needs.publish-core.outputs.list_plugins)}}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system hatch
          uv pip install --system --index-url https://test.pypi.org/simple/ ${{ matrix.plugin }}

      - name: Build plugin wheel
        run: |
          cd ${{ matrix.plugin }}
          hatch build
          hatch version $(date +%s)

      - name: Publish plugin to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{ matrix.plugin }}/dist/
